### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by SomnusWu** [yungfan/SMSSMSContentObserver#1]
这个拦截是获取信息中的最后一条信息来做处理 ， 正常手机发送拦截是可以的，但是一般来说app获取验证码不会是正常手机发送的，都是什么106打头的，比如：嘀嘀专车 1069014216..... 

然而这类短信会被系统默认归纳到 “通知类消息” 或者“拦截短信” 中 ， 请问 楼主这种情况如何处理呢 。

**Comment by yungfan** [comment]
一般这个功能都会集成在App中的，如支付宝，所以开发者对公司的短信接口是知道的，他们的短信也是有规律的，他们可以直接拦截。如果你的短信被第三方软件拦截了如360等，那应该是没办法的吧。

**Comment by SomnusWu** [comment]
手机没有安装360之类的 ，手上这部手机是 小米3  经过测试一些电话号码是拦截不了的 ，比如 10086 ，但是自己给自己发送是可以监听到的 。

**Comment by yungfan** [comment]
你换一部手机试试 有些手机是不会像小米这样把信息归类的 可能是小米自己归类的 底层改了 那就没办法了

**Comment by SomnusWu** [comment]
en , 但是我看也有软件能实现的.   ths

**Comment by yungfan** [comment]
那我就不知道了 也许他用的不是我这种方案
